# Regresión lineal en Python
## El paquete scikit-learn para regresión lineal y la selección de rasgos

Ya incluye metodos que automatisan la seleccion de las variables predictoras mas importantes que deben formar parte del modelo de prediccion, se realiza con una seleccion hacia atras, ELIMINACION DE RASGOS RECURSIVA

In [1]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("../a_udemy_big_data/python-ml-course-master/datasets/ads/Advertising.csv")

In [3]:
# Nombres de las columnas de rsagos de predicion, las candidatas a ser variables predictivas
feature_cols = ["TV", "Radio", "Newspaper"]

In [4]:
X = data[feature_cols] # Parte X perteneciente a alguna de las tres columnas
Y = data["Sales"] # Variables a predecir del data set columnas de vesntas

In [5]:
estimator = SVR(kernel="linear") # Estimador con el tipo de kernel lineal
selector = RFE(estimator, n_features_to_select=2, step=1)
selector = selector.fit(X,Y)

In [6]:
# Resultado de las variables predictoras seleccionadas
selector.support_

array([ True,  True, False])

In [14]:
# Significatividad con respecto al modelo
selector.ranking_

array([1, 1, 2])

In [15]:
# Implemetacion de la regrecion lineal de SKLEARN
from sklearn.linear_model import LinearRegression

In [9]:
X_pred = X[["TV", "Radio"]]

In [10]:
# Ajustar las variables predictoras para la columna de salida, vetas sale
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression()

In [11]:
lm.intercept_

2.9210999124051362

In [12]:
lm.coef_

array([0.04575482, 0.18799423])

In [13]:
# Valor de r cuadrado (R**2)
lm.score(X_pred, Y)

0.8971942610828956